export const WIKI_LOAD = 'WIKI_LOAD';
export const WIKI_LOAD_SUCCESS = 'WIKI_LOAD_SUCCESS';
export const WIKI_LOAD_FAIL = 'WIKI_LOAD_FAIL';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const ADD_PEOPLE = 'ADD_PEOPLE';
export const ADD_PEOPLE_SUCCESS = 'ADD_PEOPLE_SUCCESS';
export const ADD_PEOPLE_FAIL = 'ADD_PEOPLE_FAIL';
export const RESET_PEOPLE_SAVED = 'RESET_PEOPLE_SAVED';